### PR TITLE
allow version 1.x of gen_stage

### PR DESCRIPTION
**Pull request by danielkay**

### CODE REVIEW

**Comment by danielkay** [comment]
Apologies - intended to make this PR against my fork while I test some stuff! Doesn't look like much has changed in `gen_stage` between `v0.14.3` and `v1.0.0` so fingers crossed this will just work!

**Comment by blatyo** [comment]
Yea, thanks for taking that on. Happy to merge and release a new version.

**Comment by danielkay** [comment]
All good @blatyo - thanks for getting this adapter together in the first place! Top stuff 😄 
Have now tested this locally against gen_stage v1.0.0 and it appears to be working without hitch 👍

**Comment by danielkay** [comment]
Ooops, just realised dependabot had this covered already - closing in favour of #39

**Comment by blatyo** [comment]
Support for 1.X was added to the newest version

**Comment by danielkay** [comment]
Wonderful, thanks @blatyo :)

**Pull request closed without merging**
